### ISSUE TITLE
why accuracy, similarity, best is zero?

### ISSUE THREAD

**Issue by vince2003** [Pay20Y/SEED#26]
Hello,
Thank you for your code. However, when I run your code, I have the problem such as accuracy, similarity, best is zero.
Can you help?
![Screenshot from 2021-06-04 18-45-06](https://user-images.githubusercontent.com/39032947/120783186-bbea5f00-c565-11eb-9d0d-2ff003a1c1d5.png)

Thank you!

**Comment by wanglibing727** [comment]
Have you solved this problem? I am in the same situation.

**Comment by vince2003** [comment]
I give up it :)

**Comment by wanglibing727** [comment]
> I give up it :)

I can’t find the reason.

**Comment by ZhuYi98** [comment]
You can check embed_v1_results.txt to see the results you generate and compare them with gt.
