### ISSUE TITLE
Error in beam search

### ISSUE THREAD

**Issue by JamesYang568** [Pay20Y/SEED#52]
I got `RuntimeError: "index_select_out_cuda_impl" not implemented for 'Float' `. The data type of `t_predecessors` and `t_predecessors` are Float32. Is this correct? 
And if  I change the type to long(), I got a **0** Emebedding vector cos similarity.

**Comment by YooWang** [comment]
I also encountered the same problem, but I changed to long() type and got the result successfully.

**Comment by JamesYang568** [comment]
> I also encountered the same problem, but I changed to long() type and got the result successfully.

Thanks for your prompt reply! I want to futher confirm that can you get both similarity and accuracy correctly?
