### ISSUE TITLE
解压se_aster.tar 显示文件已经损坏

### ISSUE THREAD

**Issue by wyc2015fq** [Pay20Y/SEED#9]
win下显示这个压缩文件格式未知或者数据已经被损坏

**Comment by nightfuryyy** [comment]
@wyc2015fq how can you solve this problem ? thanks

**Comment by wanlipeng** [comment]
我也是啊,请问你有解决了吗

**Comment by YooWang** [comment]
可以试一下改一下文件的名字， se_aster.pth.tar  因为他这个是和aster基本上一样的，这是aster的生成权重文件格式

**Comment by YooWang** [comment]
我刚刚试了一下，成功了，把名字改一下就行了。

**Comment by wanlipeng** [comment]
> 我刚刚试了一下，成功了，把名字改一下就行了。
你好,我这边修改名字为se_aster.pth.tar,在windows下使用压缩工具不能解压,,ubuntu下使用 tar -xvf se_aster_path.tar显示tar:This does not look like a tar archive, tar:Exitting with failure status due to previous errors,还是不正确解压,能具体说下您是通过什么方式解压的吗,感谢!!

**Comment by wanlipeng** [comment]
> 我刚刚试了一下，成功了，把名字改一下就行了。

你好,我这边修改名字为se_aster.pth.tar,在windows下使用压缩工具不能解压,,ubuntu下使用 tar -xvf se_aster_path.tar显示tar:This does not look like a tar archive, tar:Exitting with failure status due to previous errors,还是不正确解压,能具体说下您是通过什么方式解压的吗,感谢!!我本地下载模型文件大小是95.7MB,难道是下载没下完整吗?

**Comment by YooWang** [comment]
> > 我刚刚试了一下，成功了，把名字改一下就行了。
> 
> 你好,我这边修改名字为se_aster.pth.tar,在windows下使用压缩工具不能解压,,ubuntu下使用 tar -xvf se_aster_path.tar显示tar:This does not look like a tar archive, tar:Exitting with failure status due to previous errors,还是不正确解压,能具体说下您是通过什么方式解压的吗,感谢!!我本地下载模型文件大小是95.7MB,难道是下载没下完整吗?

这是一个权重文件，不需要解压的，可以直接使用的。 就是说，不用解压。

**Comment by wanlipeng** [comment]
> > > 我刚刚试了一下，成功了，把名字改一下就行了。
> > 
> > 
> > 你好,我这边修改名字为se_aster.pth.tar,在windows下使用压缩工具不能解压,,ubuntu下使用 tar -xvf se_aster_path.tar显示tar:This does not look like a tar archive, tar:Exitting with failure status due to previous errors,还是不正确解压,能具体说下您是通过什么方式解压的吗,感谢!!我本地下载模型文件大小是95.7MB,难道是下载没下完整吗?
> 
> 这是一个权重文件，不需要解压的，可以直接使用的。 就是说，不用解压。

好的,谢谢,确实是...
